#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  3 13:32:37 2021

@author: pi
"""

import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
cilinder = 12

GPIO.setup(cilinder, GPIO.OUT)

while(1):
    GPIO.output(cilinder, 0)